name: CI

on:
  push:
    paths:
      - 'trunks/**'
    branches: [ "master" ]
  pull_request:
    paths:
      - 'trunks/**'
    branches: [ "master" ]
  workflow_dispatch:

jobs:
    shellcheck:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5
        - name: Install shellcheck
          run: sudo apt-get install -qy shellcheck
        - name: Run shellcheck
          run: find . -type f -iname "*.sh" -execdir shellcheck {} + 
